### ISSUE TITLE
color issue in plot (error using patch)

### ISSUE THREAD

**Issue by perrinmeyer** [fastalgorithms/fmm3dbie#15]
(see screenshot, but there is a new issue with colors (this plotted last night..) 
![ploterror](https://github.com/fastalgorithms/fmm3dbie/assets/647534/523381e5-ecc3-4ec0-a269-bb64371e12e4)

**Comment by ahbarnett** [comment]
I don't have this problem. sphere plots fine. R2022a.4 on ubuntu.
I am pushing a bunch of @surfer docs anyway...

**Comment by perrinmeyer** [comment]
I just build fmm3dbie master on my laptop, and tried again, and it worked, which is great.  
![sphereworks](https://github.com/fastalgorithms/fmm3dbie/assets/647534/d763edde-de41-49a8-86c0-c97d778c6a01)
