### ISSUE TITLE
readthedocs is not updated from master docs!

### ISSUE THREAD

**Issue by ahbarnett** [fastalgorithms/fmm3dbie#18]
the docs/surface_reps.rst has correct (p+1)(p+2)/2 formula for VR node number.

However:
https://fmm3dbie.readthedocs.io/en/latest/surface_reps.html
is wrong.

@mrachh or others can you explain how to trigger readthedocs regen on this, asap? Thanks!

**Comment by mrachh** [comment]
This is updated now. We are also working on a user guide.
